name: Scrape Contacts

on:
  # Manual trigger from the Actions tab
  workflow_dispatch:
  # 9:00 London time daily (handles BST/GMT by month)
  schedule:
    # Mar–Oct → 08:00 UTC ≈ 09:00 London (BST)
    - cron: "0 8 * 3-10 *"
    # Nov–Feb → 09:00 UTC ≈ 09:00 London (GMT)
    - cron: "0 9 * 11-12,1-2 *"

concurrency:
  group: scrape-contacts
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          # Required secrets
          GOOGLE_SA_JSON_B64: ${{ secrets.GOOGLE_SA_JSON_B64 }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CSE_KEY: ${{ secrets.GOOGLE_CSE_KEY }}
          GOOGLE_CSE_CX:  ${{ secrets.GOOGLE_CSE_CX }}
          # Sheet/tab and behavior
          SHEET_TAB: "Sheet1"
          DEFAULT_LOCATION: "Ely"
          MAX_ROWS: "100"                 # daily budget
          PREFER_COMPANY_DOMAIN: "1"
          GUESS_GENERICS: "1"
          # Optional fallbacks (only if you’ve added them)
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
        run: python -m src.main
